### ISSUE TITLE
小目标检测

### ISSUE THREAD

**Issue by 49xiyu** [lyuwenyu/RT-DETR#10]
请问这个适用于小目标检测吗，比如航空方面的

**Comment by lyuwenyu** [comment]
应该是没问题的

1. 可以先用原版的rtdetr试一下效果 
2. 然后可以结合切图的策略优化


这里有一个案例可以参考下 https://aistudio.baidu.com/aistudio/projectdetail/6164618

**Comment by 49xiyu** [comment]
> 应该是没问题的
> 
> 1. 可以先用原版的rtdetr试一下效果
> 2. 然后可以结合
/
> 
> 这里有一个案例可以参考下 https://aistudio.baidu.com/aistudio/projectdetail/6164618

这个太妙啦

**Comment by 49xiyu** [comment]
> 应该是没问题的
> 
> 1. 可以先用原版的rtdetr试一下效果
> 2. 然后可以结合切图的策略优化
> 
> 这里有一个案例可以参考下 https://aistudio.baidu.com/aistudio/projectdetail/6164618

谢谢您的回复！我的想法是先在VOC数据集上进行迁移学习，但是在更改参数上有些手足无措，想请问您有什么好的建议吗？

**Comment by 49xiyu** [comment]
> 应该是没问题的
> 
> 1. 可以先用原版的rtdetr试一下效果
> 2. 然后可以结合切图的策略优化
> 
> 这里有一个案例可以参考下 https://aistudio.baidu.com/aistudio/projectdetail/6164618

谢谢您的建议！

**Comment by lyuwenyu** [comment]
问题不大， 可以点star关注项目 持续更新
