### ISSUE TITLE
flop计算量代码跑不通

### ISSUE THREAD

**Issue by Claraeunice** [lyuwenyu/RT-DETR#100]
我想跑出原RT-DETR
以及我基于RT-DETR的模型的  参数量和计算量

按照文档进行修改后，运行出来会出现报错

`Traceback (most recent call last):
  File "flops.py", line 16, in <module>
    paddle.flops(model, None,blob, custom_ops=None, print_detail=False)
TypeError: flops() got multiple values for argument 'custom_ops'`

我觉得很奇怪，是要修改什么参数吗？

**Comment by lyuwenyu** [comment]
https://github.com/lyuwenyu/RT-DETR/issues/72
