### ISSUE TITLE
can't predict with trained model

### ISSUE THREAD

**Issue by reza-shahriari** [lyuwenyu/RT-DETR#102]
Hi
thanks for your nice work!
I have learned a model and now i want to get predicts with my trained model.
but i don't know how to predict with the model
in eval we have results which seems to be the predictions but its many BBoxes with very low precision in it!
I need help :(

**Comment by lyuwenyu** [comment]
Using these three line. https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_pytorch/src/solver/det_engine.py#L121-L137

**Comment by reza-shahriari** [comment]
thanks for your fast answer
