### ISSUE TITLE
Help: Pytorch inference (without onnx)

### ISSUE THREAD

**Issue by aaronrmm** [lyuwenyu/RT-DETR#103]
Can I run inference on an image in just pytorch? I was able to get inference to run with the model.onnx, but I'm having a really hard time installing onnxrunetime-gpu on jetson devices and am wondering if theres another way. Thanks!

**Comment by lyuwenyu** [comment]
Of course. It can do it only these three lines

https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_pytorch/src/solver/det_engine.py#L121-L137
