### ISSUE TITLE
Question about IoU-aware query selection

### ISSUE THREAD

**Issue by rydenisbak** [lyuwenyu/RT-DETR#105]
Hello! Thank you for the great work!
Did you make experiments with IoU aware query selection from encoder?

I mean in this place
https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_paddle/ppdet/modeling/transformers/rtdetr_transformer.py#L496-L497C65

choose top 300 queries by IoU aware score, not by cls score.

If you did not experiment with this, may be you have any plan to try this?

**Comment by lyuwenyu** [comment]
In inference, we do not have `target` info, so it do not get `iou` related infos.

`cls score` is supervised by iou, so it is iou-aware.

**Comment by rydenisbak** [comment]
Exactly, we have no targets. I did not think about it. Thank you!
