### ISSUE TITLE
res34 backbone for pytorch

### ISSUE THREAD

**Issue by cmiforsaken** [lyuwenyu/RT-DETR#107]
Would you please provide the res34 config file for PyTorch？I can't replicate the res34 num when I use other optimizer params such as res18 or res50

**Comment by lyuwenyu** [comment]
You can refer to paddle version rtdetr-r34 firstly.

**Comment by lyuwenyu** [comment]
@cmiforsaken  add `rtdetr-r34` in pytorch configs
