### ISSUE TITLE
extract object embeddings

### ISSUE THREAD

**Issue by aaronrmm** [lyuwenyu/RT-DETR#109]
Is there a way to get the embeddings for a detected object to go with its class and bounding boxes, so that I can use it for downstream tasks such as object tracking?

**Comment by aaronrmm** [comment]
I think it'd be this "output" tensor that I'd want to expose? Is that correct?
https://github.com/lyuwenyu/RT-DETR/blob/5f0f43c3b10d1327f88608c79a2e02c6f52264ff/rtdetr_pytorch/src/zoo/rtdetr/rtdetr_decoder.py#L256

**Comment by lyuwenyu** [comment]
Yes, I think the `output` is your need
