### ISSUE TITLE
换visdrone数据集，AP、AR为0

### ISSUE THREAD

**Issue by 49xiyu** [lyuwenyu/RT-DETR#11]
您好，我使用了官网的预训练模型，来训练visdrone数据集
设置每2轮输出一次，但是我很诧异，跑了4轮，两次输出的AP、AR都是0
我仔细检查了各种配置，觉得并没有其他问题，也是跟着PP飞桨的项目做的，但就是得不到正确的结果
实在不知道该如何处理，期待您的回复
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

**Comment by 49xiyu** [comment]
> 先参考一下这个问题 桨[桨/桨检测#8431](https://github.com/PaddlePaddle/PaddleDetection/issues/8431)
> 
> （ps. 可以先星本项目 持续关注动态）

好的，我再试试，有结果再来反馈

**Comment by 49xiyu** [comment]
> > 先参考一下这个问题 桨[桨/桨检测#8431](https://github.com/PaddlePaddle/PaddleDetection/issues/8431)
> > （ps. 可以先星本项目 持续关注动态）
> 
> 好的，我再试试，有结果再来反馈

一编译以及执行训练语句就会出现这样的问题
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory我的也是这样，但是安装10.2的cuda好像还要安装cudnn，这个之前我试过非常麻烦

**Comment by 49xiyu** [comment]
> 先参考一下这个issue [PaddlePaddle/PaddleDetection#8431](https://github.com/PaddlePaddle/PaddleDetection/issues/8431)
> 
> (ps. 可以先star本项目 持续关注动态)

一编译以及执行训练语句就会出现这样的问题
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory我的也是这样，但是安装10.2的cuda好像还要安装cudnn，这个之前我试过非常麻烦

**Comment by lyuwenyu** [comment]
https://github.com/lyuwenyu/RT-DETR/issues/3
