### ISSUE TITLE
RT-DETR-R34 pytorch model

### ISSUE THREAD

**Issue by 666zz666** [lyuwenyu/RT-DETR#114]
您好，感谢您这优异的工作！！！
请问您有打算release RT-DETR-R34这个模型的pytorch模型嘛？或者是否可以更新一下paddle转pytorch的脚本？

**Comment by lyuwenyu** [comment]
好的 近期我会更新一下r34的模型；  可以持续关注动态

**Comment by 666zz666** [comment]
非常感谢！！！

**Comment by lyuwenyu** [comment]
@666zz666  已更新
