### ISSUE TITLE
两处报错

### ISSUE THREAD

**Issue by victor1993tju** [lyuwenyu/RT-DETR#116]
index created!
number of params: 42700515
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

rtdetr_pytorch/tools/../src/zoo/rtdetr/box_ops.py", line 52, in generalized_box_iou
    assert (boxes1[:, 2:] >= boxes1[:, :2]).all()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by lyuwenyu** [comment]
先参考这两个issue的问题和定位具体报错信息的方法 https://github.com/lyuwenyu/RT-DETR/issues/70 https://github.com/lyuwenyu/RT-DETR/issues/99
