### ISSUE TITLE
Doubt regarding transformation 

### ISSUE THREAD

**Issue by rafaelpadilla** [lyuwenyu/RT-DETR#126]
Thank you for sharing the code :) 

Looking at the the project, I had a doubt in one part regarding one transformation.

Could someone please, give me some help in understanding which cases the `reference_points.shape[-1]` can fall in these cases: being either 2 or 4 [here](https://github.com/lyuwenyu/RT-DETR/blob/3330eca679a7d7cce16bbb10509099174a2f40bf/rtdetr_pytorch/src/zoo/rtdetr/rtdetr_decoder.py#L122-L132)?

I really appreciate your help

**Comment by lyuwenyu** [comment]
`reference_points.shape[-1] == 2:` means input `reference_points` is a `point` type  to sample feature
`reference_points.shape[-1] == 4` means input `reference_points` is a `box` type to sample feature

In rtdetr, `reference_points` is box type

**Comment by rafaelpadilla** [comment]
Thank you :)
