### ISSUE TITLE
YoloNAS comparison

### ISSUE THREAD

**Issue by Ryanshuai** [lyuwenyu/RT-DETR#132]
Hi, 
看论文里没有关于YoloNAS的对比。Yolo系列最新SOTA应该是YoloNAS。
想问有关于YoloNas的对比结果吗？

**Comment by lyuwenyu** [comment]
没有对比   1. rtdetr比YoloNas早 2. 条件不一样 不太能直接对比的

**Comment by Ryanshuai** [comment]
感谢回复。
