### ISSUE TITLE
VFL Loss Won't Converge.

### ISSUE THREAD

**Issue by thisistejaspandey** [lyuwenyu/RT-DETR#139]
Since the VFL loss is an IOU-aware classifier, I'd assume classification and bounding box losses should converge even faster.

However, in my case the losses tend to diverge. Do you have any intuition behind why this would be the case?
<img width="1413" alt="Screenshot 2023-11-24 at 8 53 24 AM" src="https://github.com/lyuwenyu/RT-DETR/assets/10881282/5a37af85-be11-4c22-8586-56ebcb9093ef">

**Comment by lyuwenyu** [comment]
Is the `mAP` normal?

**Comment by thisistejaspandey** [comment]
I'm training on a custom dataset and the mAP goes down. I feel like the size of the object plays a role in how good the loss works maybe? I have a dataset with lots of small objects.
