### ISSUE TITLE
Paper Figure Confusion

### ISSUE THREAD

**Issue by vjsrinivas** [lyuwenyu/RT-DETR#142]
Hello,

Thank you for your work. I was reading the paper and was confused on Figure 6:

![image](https://github.com/lyuwenyu/RT-DETR/assets/5075453/0f585358-9f0a-43dc-a67e-6a51d1994b77)

From the caption, there should be blue **and** red points but there's only blue. I'm assuming the figure is supposed to show how IoU-based query selection has less points where classification is high and IoU ~= 0 compared to the vanilla query selection.

**Comment by lyuwenyu** [comment]
Sorry for that, I don't know why arxiv can't be displayed anymore.  You can check below figure

<img width="500" alt="image" src="https://github.com/lyuwenyu/RT-DETR/assets/17582080/ab921a62-bb03-4631-b7d2-1a01843235cf">
