### ISSUE TITLE
模型参数修改问题

### ISSUE THREAD

**Issue by clk-ad** [lyuwenyu/RT-DETR#146]
你好，想请问一下为什么修改RT-DETR-main/rtdetr_pytorch/configs/dataset/coco_detection.yml里面的batch_size参数没有用？在自己数据集上跑实验时，好像batch_size一直为4，修改了也没用。

**Comment by tommyjiang** [comment]
要修改 `RT-DETR-main/rtdetr_pytorch/configs/rtdr/include/dataloader.yml` 里面的 `batch_size`
