### ISSUE TITLE
计算量和参数量

### ISSUE THREAD

**Issue by todesti2** [lyuwenyu/RT-DETR#148]
我已经阅读过所有有关的issues和文档说明，但还是跑不出来
请问有人跑出来了吗，能给我一个指令吗？
这是我的指令和结果

`(paddlepaddle) root@autodl-container-6b1911bd52-d696bc56:~/RT-DETR/rtdetr_paddle# python flops.py 

WARNING: OMP_NUM_THREADS set to 12, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
PLEASE USE OMP_NUM_THREADS WISELY.
W1201 09:06:51.720057  1005 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.2
W1201 09:06:51.723688  1005 gpu_resources.cc:149] device: 0, cuDNN Version: 8.1.
Traceback (most recent call last):
  File "flops.py", line 14, in <module>
    paddle.flops(model, None, blob, custom_ops=None, print_detail=False)
TypeError: flops() got multiple values for argument 'custom_ops'`

**Comment by Claraeunice** [comment]
> #72

您好，这并没有解决我的问题。可以i麻烦您仔细看下我上面的问题嘛？我已经被这个困扰四个多月了一直没有头绪

**Comment by lyuwenyu** [comment]
我这边按照流程操作没问题的  另外我看其他同学也跑出来了，   你这边应该是文档里第一步没改对

**Comment by Claraeunice** [comment]
> 我这边按照流程操作没问题的 另外我看其他同学也跑出来了， 你这边应该是文档里第一步没改对

好的，我再仔细尝试一下，我也觉得是我领会错了文档的意思，我再仔细尝试一下

我想得到的是：
我对RT-DETR添加tricks后训练出来的模型    的参数量和计算量

步骤：
用第一步的代码替换对应文件中的flops函数。
接着在RT-DETR/rtdetr_paddle下执行第二步的代码

问题：
出现了上面的报错

**Comment by Claraeunice** [comment]
`(paddlepaddle) root@autodl-container-7f4a118652-cfc744a2:~/miniconda3/lib/python3.8/site-packages/paddle/hapi# python
Python 3.8.17 (default, Jul  5 2023, 21:04:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
WARNING: OMP_NUM_THREADS set to 12, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
PLEASE USE OMP_NUM_THREADS WISELY.
>>> from ppdet.core.workspace import load_config, merge_config
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
>>> from ppdet.core.workspace import create
>>> cfg_path = '/root/RT-DETR/rtdetr_paddle/configs/rtdetr/rtdetr_r50vd_6x_coco.yml'
>>> cfg = load_config(cfg_path)
>>> model = create(cfg.architecture)
W1211 17:48:02.074813  1416 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.2
W1211 17:48:02.081236  1416 gpu_resources.cc:149] device: 0, cuDNN Version: 8.1.
>>> blob = {
...     'image': paddle.randn([1, 3, 640, 640]),
...     'im_shape': paddle.to_tensor([[640, 640]]),
...     'scale_factor': paddle.to_tensor([[1., 1.]])
... }
>>> paddle.flops(model, None, blob, custom_ops=None, print_detail=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: flops() got multiple values for argument 'custom_ops'`



怎么执行都是这个问题，是第一步的代码除了替换还需要更改什么嘛

**Comment by Claraeunice** [comment]
> 我这边按照流程操作没问题的 另外我看其他同学也跑出来了， 你这边应该是文档里第一步没改对

等等！我发现了一个问题！
dynamic_flops.py中还存在下面的文件们这里的参数没有input_size !
def dynamic_flops(model, inputs, custom_ops=None, print_detail=False):

我想这就是造成问题的根源！所以参数不对应

您的意思是用第一部分的代码替换dynamic_flops.py中所有的代码嘛？？？

**Comment by lyuwenyu** [comment]
第一步怎么替换的 替换之后的文件upload看下

**Comment by Claraeunice** [comment]
> 第一步怎么替换的 替换之后的文件upload看下

感谢您的回复，我是完整替换了里面原有的def flops()函数
![image](https://github.com/lyuwenyu/RT-DETR/assets/97581575/7f5e3796-8c06-4c01-ad55-6d9d48dfb4e6)

**Comment by Claraeunice** [comment]
紧接着创建get.py，将第二部分代码放进去并将cfg_path改成绝对路径
![image](https://github.com/lyuwenyu/RT-DETR/assets/97581575/8502e39c-dfe4-4860-a44b-2bb1ccfc6f21)

通过 python get.py
就出现报错：
Traceback (most recent call last): 
File "get.py", line 14, in <module> paddle.flops(model, None, blob, custom_ops=None, print_detail=False) 
TypeError: flops() got multiple values for argument 'custom_ops'

**Comment by Claraeunice** [comment]
> 紧接着创建get.py，将第二部分代码放进去 ![image](https://private-user-images.githubusercontent.com/97581575/289535389-8502e39c-dfe4-4860-a44b-2bb1ccfc6f21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTgyMzksIm5iZiI6MTcwMjI5NzkzOSwicGF0aCI6Ii85NzU4MTU3NS8yODk1MzUzODktODUwMmUzOWMtZGZlNC00ODYwLWE0NGItMmJiMWNjZmM2ZjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyMzIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MTY4MzczNzI1YmNhYWRkYmZhZDZjODYzY2Q4NGNjNzgxZTM1MTI0YmMwZTZjOGQ2YTk0NTQyNTc2YWNlZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bsrdmK5EesKVAb-rxX-eK-EUyv92LGs4ue1W7fXzxUo)
> 
> 通过 python get.py 就出现报错： Traceback (most recent call last): File "get.py", line 14, in paddle.flops(model, None, blob, custom_ops=None, print_detail=False) TypeError: flops() got multiple values for argument 'custom_ops'

**Comment by lyuwenyu** [comment]
1. 你在flops函数里随便加一行 比如在30行 + print('xxx') ；看看走这个函数了嘛
2. get.py不需要放到hapi下面  在你工作目录随便找个地方放

**Comment by Claraeunice** [comment]
> 1. 你在flops函数里随便加一行 比如在30行 + print('xxx') ；看看走这个函数了嘛
> 2. get.py不需要放到hapi下面  在你工作目录随便找个地方放


![image](https://github.com/lyuwenyu/RT-DETR/assets/97581575/722fee79-56ad-4868-b733-67eb04560e6d)

已经按照您说的做了，但是很震惊的是没有经过这个函数！！
![image](https://github.com/lyuwenyu/RT-DETR/assets/97581575/7a48c494-36cb-4ee3-bda2-810d4b816b34)

**Comment by Claraeunice** [comment]
> > 1. 你在flops函数里随便加一行 比如在30行 + print('xxx') ；看看走这个函数了嘛
> > 2. get.py不需要放到hapi下面  在你工作目录随便找个地方放
> 
> ![image](https://private-user-images.githubusercontent.com/97581575/289537659-722fee79-56ad-4868-b733-67eb04560e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTg2NDYsIm5iZiI6MTcwMjI5ODM0NiwicGF0aCI6Ii85NzU4MTU3NS8yODk1Mzc2NTktNzIyZmVlNzktNTZhZC00ODY4LWI3MzMtNjdlYjA0NTYwZTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyMzkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OTVkZmU3ZmRiYWY4MTMwZWEwMTVjNzlmYWQ5NDdlYTEwMjA4NGFmZmQzOGU3ZjVkYzdmYjFmMTA5NzhlNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MqZRyLzHI1plapextTtsKPuyG-Tp5saYY00tJTsF9JE)
> 
> 已经按照您说的做了，但是很震惊的是不管是否缩进，都没有经过这个函数！！ ![image](https://private-user-images.githubusercontent.com/97581575/289537491-7a48c494-36cb-4ee3-bda2-810d4b816b34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTg2NDYsIm5iZiI6MTcwMjI5ODM0NiwicGF0aCI6Ii85NzU4MTU3NS8yODk1Mzc0OTEtN2E0OGM0OTQtMzZjYi00ZWUzLWJkYTItODEwZDRiODE2YjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyMzkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OTE0OWZlYWI2ZGI2NGM3NGZlNjM4NGYzZWQ4MjQ5ZmYxMjliNzFkMTZhNWYxOTczNDlmMmUzYmQ2MTQ5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7jWAURfQTWv2WDww3WEkLMhcCrEt5CB9D-IWnWQEXrU)

**Comment by lyuwenyu** [comment]
1. 确认下你用的是那个python以及paddle安装位置
```bash
which python

```

**Comment by Claraeunice** [comment]
> 1. 确认下你用的是那个python以及对应的paddle安装位置 （一般`paddle`在对应python环境的`site-packages`下）
> 
> ```shell
> which python
> ```


天呐，原来是在这里！！！刚改掉成功输出了！！！我宣布你是我最喜爱的作者没有之一5555
我四个月的困扰终于解决了！！！
感谢感谢！！❤❤太厉害了向你学习！！
![image](https://github.com/lyuwenyu/RT-DETR/assets/97581575/7eb42b35-068c-4c39-b164-cdef7722ef8f)

**Comment by Claraeunice** [comment]
> 在你这环境下吧 <img alt="image" width="300" src="https://private-user-images.githubusercontent.com/17582080/289539462-1988e981-0605-437e-a315-ae84fa16dd33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTkwNDksIm5iZiI6MTcwMjI5ODc0OSwicGF0aCI6Ii8xNzU4MjA4MC8yODk1Mzk0NjItMTk4OGU5ODEtMDYwNS00MzdlLWEzMTUtYWU4NGZhMTZkZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyNDU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNDYwOWY5NTU5NzRiNGI0OTNkYjNiY2NjNDkyNzA5NGJmNWNiY2FiY2QxZDhjNGM2ODE1MmEwNGNkNGQ2NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zsx4gPFpWgnasVXFL3TFSyWeLpbHy712rmjwaC79kwA">

是的，我深刻认识到了这个问题！泪的教训！！爱你作者！！！
