### ISSUE TITLE
pytorch版本复现，没有达到论文精度

### ISSUE THREAD

**Issue by 1747956LXR** [lyuwenyu/RT-DETR#182]
我使用一张3090显卡复现pytorch版的rt-detr，复现的模型为rtdetr_r18vd_6x_coco.yml，设置的batchsize=16，其他参数和代码都没有改变，最后得到45.9的mAP，与论文报告的46.5的mAP还有差距，以下是训练最后几个epoch的截图，有劳作者帮忙看一下，谢谢！
![image](https://github.com/lyuwenyu/RT-DETR/assets/39217603/f16cbca4-cdb8-490c-9994-14c840123536)

**Comment by lyuwenyu** [comment]
这个版本我只跑了r50的 log放这里了https://github.com/lyuwenyu/RT-DETR/issues/42

ps.
另外我重新设计了pytorch版本的rtdetrv2_r18的精度mAP 47.9  https://github.com/lyuwenyu/RT-DETR/issues/179

可以先star这个repo并持续关注一下后续的状态

**Comment by chhchhchh** [comment]
@1747956LXR 你好，你的3090卡显存资源大概是多大的？
