### ISSUE TITLE
RT-DETR-R50-m 和RT-DETR-R50的区别是啥呀

### ISSUE THREAD

**Issue by xiaohangguo** [lyuwenyu/RT-DETR#186]
可以介绍一下RT-DETR-R50-m 和RT-DETR-R50的区别吗，论文中结果好像没有？是关于尺寸做了变化吗

**Comment by lyuwenyu** [comment]
1. encoder expansion参数不一样
2. decoder的层数不一样

`RT-DETR-R50-m`是为了表明rtdetr结构的灵活性，给的一个调节结构的例子
