### ISSUE TITLE
problem about training with my own dataset using only single class

### ISSUE THREAD

**Issue by john09282922** [lyuwenyu/RT-DETR#19]
Hi, 
thanks for nice works. 
I looked into issues this git and paddle git as well. I could not find how to fix training method with RT-DETR for sing class object detection. Because when using coco and visdrone, rt-detr was good, but my dataset is not good comparing with Yolov8. Can you tell me how to increase mAP for single class training?

and paddle has data augmentation method? 

thansk

**Comment by lyuwenyu** [comment]
Which repo do you use, this repo or paddledetection?

---
( star this repo and keep following.

**Comment by lyuwenyu** [comment]
I think your can try this repo (experiment code) firstly to except PaddleDetection was injected bugs for some pr.

**Comment by lyuwenyu** [comment]
paddle code in here.  https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_paddle
