### ISSUE TITLE
resnet50的热力图

### ISSUE THREAD

**Issue by todesti2** [lyuwenyu/RT-DETR#191]
请问一下，如何在RT-DETR的resnet50的最后一层，画出grad cam热力图呢

**Comment by lyuwenyu** [comment]
这个目前仓库不支持的 你得找个第三方库去可视化，，可以在这找到最后一层的特征 https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_pytorch/src/nn/backbone/presnet.py#L215

**Comment by todesti2** [comment]
> 这个目前仓库不支持的 你得找个第三方库去可视化，，可以在这找到最后一层的特征 https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_pytorch/src/nn/backbone/presnet.py#L215

哎 好吧，谢谢您

**Comment by Ryanshuai** [comment]
可以看下这个： https://github.com/jacobgil/pytorch-grad-cam

**Comment by todesti2** [comment]
> 可以看下这个： https://github.com/jacobgil/pytorch-grad-cam

谢谢您，可是我用的是paddle框架……好多人都说做不了
