### ISSUE TITLE
RT-DETR如何输出特征图

### ISSUE THREAD

**Issue by todesti2** [lyuwenyu/RT-DETR#193]
请问，resnet50作为backbone的RT-DETR可以输出特征图吗？怎么做呢？我好久都找不到解决办法

**Comment by lyuwenyu** [comment]
可以吧 找到对应的代码位置 直接save一个tensor？看看能满足你需求不

**Comment by todesti2** [comment]
> 可以吧 找到对应的代码位置 直接save一个tensor？看看能满足你需求不

还是不知道该如何做，找了各种资料，请问桨桨有什么输出特征图的教程吗

**Comment by todesti2** [comment]
> 可以吧 找到对应的代码位置 直接save一个tensor？看看能满足你需求不

请问怎么做呀，哪里都找不到教程，新手很窘迫
