### ISSUE TITLE
推理图片的一种类别能否对应一种颜色

### ISSUE THREAD

**Issue by todesti2** [lyuwenyu/RT-DETR#194]
您好，在推理图片过程中，我发现图片中类别的预测对应颜色是随机的？每张图片同一类别的颜色不同，这似乎不太美观。
但是我没有找到颜色的那个文件，通过搜COLOR我也不能确定。
请问您可以指点一下设置颜色的文件在哪里吗？

**Comment by Mahonehan** [comment]
有推理图片的代码吗？怎么可视化

**Comment by todesti2** [comment]
> 有推理图片的代码吗？怎么可视化

你可以看参考文档  python tools/infer.py那个

**Comment by Mahonehan** [comment]
我用的是pytorch的哪个版本，刚才看了下issue，解决了怎么推理
https://github.com/lyuwenyu/RT-DETR/issues/136#issuecomment-1876722312

**Comment by todesti2** [comment]
> 我用的是pytorch的哪个版本，刚才看了下issue，解决了怎么推理 [#136 (comment)](https://github.com/lyuwenyu/RT-DETR/issues/136#issuecomment-1876722312)

好的  麻烦你删除一下你的问题好嘛哈哈
