### ISSUE TITLE
Image size for custom dataset

### ISSUE THREAD

**Issue by BenjaminJonghyun** [lyuwenyu/RT-DETR#229]
Hello, thank you for sharing codes.

I'd like to train your model on my custom dataset, which has 640x480(width, height) size.
The image size should be fixed to keep aspect ration of the original size.

So, which lines in codes should be modified?
In my insight,
[dataloader.yml](https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_pytorch/configs/rtdetr/include/dataloader.yml)
L14 and L33 are set to be [480, 640]
[rtdetr_r50vd.yml](https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_pytorch/configs/rtdetr/include/rtdetr_r50vd.yml)
L43 and L58 are set to be [480, 640]

please check it.

**Comment by lyuwenyu** [comment]
Yes.
