### ISSUE TITLE
如何得到测试集mAP等

### ISSUE THREAD

**Issue by 49xiyu** [lyuwenyu/RT-DETR#25]
1.在训练过程中启动评估，会得到验证集的map，但是训练过程中输出的loss貌似是训练集的，那么该怎么得到验证集的loss呢

2.推理测试集只能得到一堆图片和bbox.json，也得不到map。

3.非常苦恼，因为我训练过程中的loss降到16左右就开始徘徊，我不知该如何判断过拟合

期待并感谢您的回复！

**Comment by Di-Zhu123** [comment]
请问是怎么解决的
