### ISSUE TITLE
changing backbone

### ISSUE THREAD

**Issue by hweejuni** [lyuwenyu/RT-DETR#274]
Hi. Thank you for your hard work.

I'm trying to change the backbone (currently resnet50) for further ablation but the part related to manipulating backbone seems complicated. I want to apply torchvision's models or timm models. What is the most efficient way to change backbone? I am struggling. Thanks.

**Comment by lyuwenyu** [comment]
You should `register` the torchvision or timm model firstly, then using it in yaml config.

**Comment by ramonhollands** [comment]
@hweejuni Any success? Would be interesting to hear from!

**Comment by hweejuni** [comment]
Hi. I imported timm's CSPResNet model (the raw code) and got the training worked.
What I did was, I added cspnet.py, added register decorator, adjusted dimension size of the cspnet output, and added cspnet import to __init__.py (It took me long time to understand how registere works haha).

**Comment by ramonhollands** [comment]
See https://github.com/lyuwenyu/RT-DETR/issues/332 for adding timm backbones
