### ISSUE TITLE
关于trt模型推理

### ISSUE THREAD

**Issue by NeKoooo233** [lyuwenyu/RT-DETR#279]
那个，我现在导出了trt模型，按照readme里面的教程，可以使用trtinfer.py进行推理，尽管这非常简单，我尝试了将文件中的engine_path改为模型路径，并运行python trtinfer.py(大概不是这么用的)，但是并没有起作用，我想知道怎么使用trtinfer.py
=.=

**Comment by lyuwenyu** [comment]
```
blob = {
    'images': im
    'orig_target_sizes': orig_size,
}

m = TRTInference('path/to/engine')
r = m(blob)
```
