### ISSUE TITLE
关于通道数问题

### ISSUE THREAD

**Issue by 49xiyu** [lyuwenyu/RT-DETR#29]
ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 64, the input's shape is [4, 64, 160, 160]; the filter's channels is 128, the filter's shape is [64, 128, 1, 1]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:64 != filter_dims[1] * groups:128.] (at ../paddle/phi/infermeta/binary.cc:534)

**Comment by lyuwenyu** [comment]
改啥了
