### ISSUE TITLE
当RT-DETR的backbone为ResNet50或ResNet101时，训练COCO2017数据集，训练时eval的map一直是0

### ISSUE THREAD

**Issue by wmjlincy** [lyuwenyu/RT-DETR#3]
大佬好，当我用RT-DETR的backbone为ResNet50训练COCO2017数据集时，训练过程中eval的mAP一直是0，且loss在不断下降，pretrain_weights加载的是ResNet50_vd_ssld_v2_pretrained.pdparams，其他参数没做改动；除此之外，每次eval保存的bbox.json文件中，每张图片保存了300个检测框，但是每个检测框的类别、box位置和score都是一样的，请问我需要怎么解决呢？非常期待大佬能够回答一下我的问题，感激不尽~

下面是我训练时的环境：
我用的是PaddlePaddle 2.4.2的镜像，CUDA是11.8。

**Comment by lyuwenyu** [comment]
用这版代码先试一下 我跑了r18验证 好像没啥问题，

**Comment by wmjlincy** [comment]
你好，我试了一下，用这版代码跑R50没问题了，感谢大佬~

**Comment by lkz98** [comment]
> 用这版代码先试一下 我跑了r18验证 好像没啥问题，

你好，请问是哪版代码啊
