### ISSUE TITLE
RT-DETR训练更多Epoch(>72)是否还有性能提升

### ISSUE THREAD

**Issue by butn345** [lyuwenyu/RT-DETR#30]
请问，RT-DTR训练更多个Epoch（>72）后检测性能还会提升吗，有训练过程的log信息可以给我参考一下吗？训练更多个Epoch可能会有过拟合的问题吗？

**Comment by lyuwenyu** [comment]
可以参考下面的log


<img width="1051" alt="image" src="https://github.com/lyuwenyu/RT-DETR/assets/17582080/39edd1a7-522e-457f-ab79-4cd15a849629">

**Comment by butn345** [comment]
感谢您的回复，我看了这个只有72个Epoch的log信息；不知道您是否尝试过训练更多epoch，比如128个甚至更多，如果有，那么在72个Epoch后的训练中检测性能还会有明显提升吗

**Comment by lyuwenyu** [comment]
我们训练过 7x   从曲线上看是不涨点了
