### ISSUE TITLE
loss值无法下降

### ISSUE THREAD

**Issue by todesti2** [lyuwenyu/RT-DETR#304]
作者您好，我使用RT-DETR训练了72轮，精度没有异常，但是我发现它的损失值一直在18左右徘徊，无法下降，这是为什么呢？我换了其他数据集也是如此

**Comment by lyuwenyu** [comment]
一开始是多少 可以把loss曲线画出来

**Comment by todesti2** [comment]
> 一开始是多少 可以把loss曲线画出来
一开始是三十多，过了个几轮就到了18左右，到最后都是18左右

**Comment by todesti2** [comment]
> 一开始是多少 可以把loss曲线画出来

一开始是三十多，过了个几轮就到了18左右，到最后都是18左右

**Comment by todesti2** [comment]
> 一开始是多少 可以把loss曲线画出来

您好，这个loss变化是正常的吗

**Comment by hzy-del** [comment]
> 您好，这个loss变化是正常的吗

你好，我也有这个问题，请问你解决了吗

**Comment by diliess** [comment]
我也遇到了这个情况 请问是没有收敛吗
