### ISSUE TITLE
主干加载预训练权重复现问题

### ISSUE THREAD

**Issue by ainawen** [lyuwenyu/RT-DETR#313]
作者您好，根据您之前提供的训练日志https://github.com/lyuwenyu/RT-DETR/files/13059685/log_rtdetr_r50vd_coco_pytorch.txt，请问这是加载在imagenet1k上预训练的resnet50主干，跑出来的coco成绩吗？如果不加载预训练主干，从零开始训练进行coco数据集上的复现是不是会有精度上的损失？

**Comment by lyuwenyu** [comment]
是的， 不加载的话默认配置下精度可能会掉  1. 从0训练需要的时间长 2. 并且需要精心调学习策略 (模型是CNN和Transformer的混合体)

**Comment by ainawen** [comment]
好的，谢谢您的回复

**Comment by chhchhchh** [comment]
你好，请问如果在不加载预训练权重的情况下，精度可能会掉几个点左右？

**Comment by ainawen** [comment]
> 你好，请问如果在不加载预训练权重的情况下，精度可能会掉几个点左右？

我这边r18在100轮下是掉3个点

**Comment by chhchhchh** [comment]
感谢您的回复，不知同学有没有试过r50，感觉掉点在6以上了吧
