### ISSUE TITLE
关于uncertainty-minimal Query Selection

### ISSUE THREAD

**Issue by Nicole-1996** [lyuwenyu/RT-DETR#321]
这部分我好像没有在代码里看到，我找到的_get_decoder_input函数似乎依旧是根据类别概率选择初始的query，能请问一下uncertainty-minimal Query Selection在代码里的那部分有体现么？或者由于版本更迭，目前的代码与4月份那一版的论文有出入？

**Comment by Xujiajing111** [comment]
同问
