### ISSUE TITLE
The charts in the paper is beautiful！How to draw it？

### ISSUE THREAD

**Issue by TaroPlay** [lyuwenyu/RT-DETR#34]
作者您好，感谢您开源了代码，论文中您的图表也十分美观，我想请问关于IOU aware query（similar to VFL）的部分，Figure 6的散点图是如何画出来的呢，有提供脚本工具绘制吗，如果有的话可以说一下在哪里吗？十分期待您的回复！！

**Comment by lyuwenyu** [comment]
使用matplotlab画的散点图   代码是临时写的的 有时间整理一下，，， 可以star本项目 持续关注动态
