### ISSUE TITLE
查看backbone：hgnet_v2

### ISSUE THREAD

**Issue by 49xiyu** [lyuwenyu/RT-DETR#35]
您好，感谢您做出的工作和之前耐心的回复！！
我想请问在哪里可以看到RT-DETR的hgnet_v2网络结构图呢？目前我只找到了hgnet。十分期待并感谢您的回复！！

**Comment by lyuwenyu** [comment]
hgnetv2目前还没有发论文 只能先看代码

**Comment by 49xiyu** [comment]
> hgnetv2目前没有发论文 只能先看代码 或者 看看网上有没有分析的图，，

好的谢谢您的回复！！！
