### ISSUE TITLE
TensorRT Inference Produces Zero Value Coordinates

### ISSUE THREAD

**Issue by rogcomfox** [lyuwenyu/RT-DETR#364]
Hi there, thank you for your great work of RT-DETR. I trained RT-DETR using my own dataset and convert the onnx model to TensorRT following this #124. when I do inference, the bounding boxes coordinates always produces zero value like this screenshot. for inference I follow your code in trtinfer.py.
![Screenshot 2024-07-11 185425](https://github.com/lyuwenyu/RT-DETR/assets/43591150/8c687415-3c00-4ef8-9beb-06d59d0a1ea9)

**Comment by rogcomfox** [comment]
for the inputs, i put all of the inputs to gpu instead of cpu like this
`#for tensor backend
resized_img = T.ToTensor()(resized_img)[None].to("cuda:0", non_blocking=True)
blob = {"images" : resized_img, "orig_target_sizes": torch.tensor([[640,640]]).to("cuda:0", non_blocking=True)}`

**Comment by lyuwenyu** [comment]
> "orig_target_sizes": torch.tensor([[640,640]]).to("cuda:0", non_blocking=True)

replace this as 
```
"orig_target_sizes": torch.tensor([[640,640]]).to(device="cuda:0", dtype=torch.int32, non_blocking=True)
```

**Comment by rogcomfox** [comment]
thank you so much for your suggestion! it finally works like a charm
![image](https://github.com/user-attachments/assets/18ae50a9-91d8-4bef-8ecd-539f643353a8)
