### ISSUE TITLE
预训练权重

### ISSUE THREAD

**Issue by lime-s** [lyuwenyu/RT-DETR#365]
您好，我想问一下，我使用下述命令进行训练：
# training on single-gpu
export CUDA_VISIBLE_DEVICES=0
python tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml
我没有指定预训练权重，这个下载的预训练权重是在哪里定义的呢

**Comment by lyuwenyu** [comment]
https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_pytorch/src/nn/backbone/presnet.py#L196
