### ISSUE TITLE
Mismatch in pytorch model state dictionary

### ISSUE THREAD

**Issue by VimukthiRandika1997** [lyuwenyu/RT-DETR#367]
There is a mismatch when loading model checkpoints for the pytorch implementation. Is this related since models were taken from padddle ?

Load model.state_dict, {'missed': [], 'unmatched': ['decoder.denoising_class_embed.weight', 'decoder.enc_score_head.weight', 'decoder.enc_score_head.bias', 'decoder.dec_score_head.0.weight', 'decoder.dec_score_head.0.bias', 'decoder.dec_score_head.1.weight', 'decoder.dec_score_head.1.bias', 'decoder.dec_score_head.2.weight', 'decoder.dec_score_head.2.bias', 'decoder.dec_score_head.3.weight', 'decoder.dec_score_head.3.bias', 'decoder.dec_score_head.4.weight', 'decoder.dec_score_head.4.bias', 'decoder.dec_score_head.5.weight', 'decoder.dec_score_head.5.bias']}

I am trying to finetune the model on a custom dataset, would this impact ?

**Comment by lyuwenyu** [comment]
> I am trying to finetune the model on a custom dataset, would this impact ?

This is normal because your dataset and `Coco`'s category are different

**Comment by VimukthiRandika1997** [comment]
> > I am trying to finetune the model on a custom dataset, would this impact ?
> 
> This is normal because your dataset and `Coco`'s category are different

Thank you for the reply, I resolved this through the findings. Basically for a custom training, those layers will be trained from scratch!. Thank you for the wonderful work!
