### ISSUE TITLE
Export to onnx get error

### ISSUE THREAD

**Issue by hongu0603** [lyuwenyu/RT-DETR#374]
使用export_onnx.py -c configs\rtdetr\rtdetr_r50vd_m_6x_coco.yml -r output\rtdetr_r50
vd_6x_coco\eval\latest.pth 要把pth 匯出時發生以下錯誤，想問是什麼原因

![image](https://github.com/user-attachments/assets/1802f129-3f8a-4f25-809a-d357ec2de745)

**Comment by lyuwenyu** [comment]
这个错应该报在加载位置了；；可以check下你加载的权重里的key

https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_pytorch/tools/export_onnx.py#L23-L27

**Comment by hongu0603** [comment]
我是用以下指令訓練自己的資料集
![螢幕擷取畫面 2024-07-17 170149](https://github.com/user-attachments/assets/2dd740ff-369a-431f-a734-fdbba4a4f0a7)
然後我直接使用
```
python tools\export_onnx.py -c configs\rtdetr\rtdetr_r50vd_6x_coco.yml -r output\rtdetr_r50vd_6x_coco\eval\latest.pth --check
``` 
會顯示以下狀況
![螢幕擷取畫面 2024-07-17 170628](https://github.com/user-attachments/assets/abfb5877-2eee-421e-97e5-425b6c1518fd)
我在yaml_utils.py中新增
![螢幕擷取畫面 2024-07-17 170704](https://github.com/user-attachments/assets/3076d21c-c417-4d74-9748-129054327003)
再跑一次則會出現 KeyError "model " ，checj 權重里的key也的確沒有model  ，想請問會是訓練中的哪一個步驟有問題呢
![螢幕擷取畫面 2024-07-17 170349](https://github.com/user-attachments/assets/0efd872d-47c1-40c9-97ac-7131051c508f)

**Comment by lyuwenyu** [comment]
`eval/lastest.pth`不是模型 是评估结果； 使用和eval同一级目录的`checkpoint-xxxx.pth`

**Comment by hongu0603** [comment]
謝謝您! 解決了
