### ISSUE TITLE
修改输入特征图尺寸

### ISSUE THREAD

**Issue by lime-s** [lyuwenyu/RT-DETR#380]
您好，我按照之前的issue修改了输入特征图尺寸，我的原图是（2448， 2048），我将其resize到（1024， 1024）确保不需要引入pad操作。具体来说，将dataloader.yml中l14和l33修改为{type: Resize, size: [1024, 1024], }以及将rtdetr_r50vd.yml中l43和l58修改为  eval_spatial_size: [1024, 1024]。但是在同一个数据集下的结果差距较大，map50：95差了6个点64.3 --> 58.4，map50差了1个点：93.2 -->92.2。是还有什么需要注意的地方么

**Comment by lime-s** [comment]
这里面的multi_scale指的是什么，会对上述精度有影响么
![截屏2024-07-24 10 37 38](https://github.com/user-attachments/assets/37c74300-0264-4909-b2dc-35eac6585e84)

**Comment by lyuwenyu** [comment]
和那个配置比掉了点呢

**Comment by lime-s** [comment]
已经解决，将multi_scale更改为以960为中位数的列表训练即可解决，这个参数是输入图片被随机resize到该尺寸然后送入模型

**Comment by xsa12345** [comment]
> 已经解决，将multi_scale更改为以960为中位数的列表训练即可解决，这个参数是输入图片被随机resize到该尺寸然后送入模型

请问这个会影响精度吗最后？
