### ISSUE TITLE
ModuleNotFoundError: No module named 'cvperception' [RTDETR-V2]

### ISSUE THREAD

**Issue by mali-afridi** [lyuwenyu/RT-DETR#396]
Hey, I wanted to try the version2, but I got there is no file named cvperception in rtdetr-pytorchv2/ folder
```
    from cvperception.core import YAMLConfig
ModuleNotFoundError: No module named 'cvperception'
```

**Comment by lyuwenyu** [comment]
which file ?

**Comment by mali-afridi** [comment]
I am trying to run  this file: python references/deploy/rtdetrv2_torch.py 
You have an import of:
` from cvperception.core import YAMLConfig `in line 11

**Comment by lyuwenyu** [comment]
relace that line as below

```python
import sys 
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent / '..' / '..'))

from src.core import YAMLConfig
```

**Comment by mali-afridi** [comment]
Thanks, works!
