### ISSUE TITLE
关于backbone改进问题

### ISSUE THREAD

**Issue by 49xiyu** [lyuwenyu/RT-DETR#40]
亲爱的作者，首先非常感谢您的工作。
我尝试用一些卷积来替换backbone的某些卷积层，但是精度要么持平要么更低。我感到非常沮丧，是backbone里面的卷积组合已经到达天花板了吗？恳请得到您的建议。

**Comment by lyuwenyu** [comment]
rtdetrd的backbone是在imagenet上经过预训练的  你直接改结构的话  相关的参数是随机初始化的  会影响性能

**Comment by 49xiyu** [comment]
> 

难怪，我各种换换了好久都得不到想要的效果，新手表示真有些力不从心。想请问一下作者您有什么建议吗？

**Comment by lyuwenyu** [comment]
不知道你改backbone的目的是啥
