### ISSUE TITLE
ValueError: Missing MyCocoDetection in inspect stage.

### ISSUE THREAD

**Issue by SongYxing** [lyuwenyu/RT-DETR#402]
作者大大您好，感谢您优秀的开源工作。

我这里是自己继承torchvision.coco重写了一个检测类，这里我就叫MyCocoDetection。

之前在v1的版本，直接写完注册调用就行了。

现在v2的版本，注册完以后还是会报这个bug，GLOBAL_CONFIG并没有注册到它，从而报这个错。

请问该如何调用自己写的类

**Comment by lyuwenyu** [comment]
类似下面的差异；

- v1
```python

@register
class MyCocoDetection(): ...

````

- v2
```python

@register()
class MyCocoDetection(): ...

````

**Comment by SongYxing** [comment]
我的天啊我这猪脑
