### ISSUE TITLE
paddle_pytorch里面的代码实现

### ISSUE THREAD

**Issue by 49xiyu** [lyuwenyu/RT-DETR#41]
尊敬的作者您好！我注意到paddle_pytorch里面有一份pytorch版本的resnet.py代码。
我看到官方在paddle_pytorch的实现步骤里是直接运行python tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml
但是我发现paddle_pytorch里面只有这一份代码，这是怎么回事呢
期待您的回复！

**Comment by lyuwenyu** [comment]
代码完善钟 还未上传
