### ISSUE TITLE
Will the training logs of rtdetrv2 be released？

### ISSUE THREAD

**Issue by fym202** [lyuwenyu/RT-DETR#411]
Will the training logs of rtdetrv2 be released？
I run rtdetrv2-r18 120 epochs and rtdetrv-r18 100epochs on coco2017_25k(Sampling 25k images from coco2017), and I get same ap on this two models. Is it because the number of training epochs for origin rtdetrv1-r18 is not enough?

**Comment by lyuwenyu** [comment]
[log_rtdetrv2_r18vd_120e_coco.txt](https://github.com/user-attachments/files/16594240/log_rtdetrv2_r18vd_120e_coco.4.txt)

**Comment by fym202** [comment]
Thank you very much! The training logs are really helpful to me!
