### ISSUE TITLE
求助:ppdet导出的模型转ONNX之后,预测报错

### ISSUE THREAD

**Issue by David-dotcom666** [lyuwenyu/RT-DETR#428]
**Star RTDETR**
请先在RTDETR主页点击**star**以支持本项目
Star RTDETR to help more people discover this project. 
环境:
paddle2.5.2
ppdet_dev和2.7都试过
onnx==1.13.0 
paddle2onnx==1.0.5 

**Describe the bug**
报错信息
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Tile node. Name:'p2o.Tile.3' Status Message: the tensor to be tiled using Tile OP must be atleast 1 dimensional
![4](https://github.com/user-attachments/assets/58dde0a6-e027-4bb7-a28a-16d9c433ddc3)

**To Reproduce**
Steps to reproduce the behavior.

**Comment by lyuwenyu** [comment]
这 自己训练的模型？用torch的也试一下

**Comment by David-dotcom666** [comment]
试了下直接下载预训练模型然后按照流程导出再转成onnx，也是报错，下面这个是因为我把onnxruntime换成了1.17的.
有没有转成onnx的模型文件啊，我想看看跟我转出来的有啥区别不
![9](https://github.com/user-attachments/assets/070cee5c-7add-4284-82fe-2e924ae2f736)

**Comment by David-dotcom666** [comment]
![onnxok](https://github.com/user-attachments/assets/35c3fa7d-d7f4-4ef1-9488-9ad90e146924)
paddle换成2.4.2后可以正常,但是不知道为什么2.4.2infer原生的paddle模型速度比2.5.2/paddle3.0b的慢了100ms(100ms->200ms)

**Comment by David-dotcom666** [comment]
> > ![onnxok](https://private-user-images.githubusercontent.com/84842493/361315157-35c3fa7d-d7f4-4ef1-9488-9ad90e146924.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjg2OTIsIm5iZiI6MTczMzEyODM5MiwicGF0aCI6Ii84NDg0MjQ5My8zNjEzMTUxNTctMzVjM2ZhN2QtZDdmNC00ZWYxLTk0ODgtOWFkOTBlMTQ2OTI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA4MzMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZTVjMDUxOGI0MzFhNmI0MjkxMGE4OTE3ZjA3Y2E2Yzg5Nzg1ZTIyZTEwZDIyMzMzNWZhNzI1ZGU0ZTg5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ff6iJr9mIoLGOYEmTEnzrTLnpbPULNRbjiHVC41pYg0) paddle换成2.4.2后可以正常,但是不知道为什么2.4.2infer原生的paddle模型速度比2.5.2/paddle3.0b的慢了100ms(100ms->200ms)
> 
> 您好，官方给出的onnx转换结果，模型貌似有图像和尺寸两个输入，会影响后续部署吗？

不懂你的意思，你是说的参数带--image XXX --img_shape [1,2,3]这种吗？我现在是导出onnx的时候固定了尺寸，部署没什么问题
