### ISSUE TITLE
Request for clarification over licensing of codebase

### ISSUE THREAD

**Issue by umarbutler** [lyuwenyu/RT-DETR#433]
I noticed that the entire codebase is meant to be licensed under Apache 2.0, however, many individual scripts have "Copyright(c) 2023 lyuwenyu. All Rights Reserved." at the top.

I would like to seek some clarification as to whether or not the entire codebase is licensed under Apache 2.0?

**Comment by lyuwenyu** [comment]
Yes, entire codebase in this repo under Apache 2.0.  You can use it with confidence under that licence.

---

**Comment by umarbutler** [comment]
Awesome, thank you!
