### ISSUE TITLE
can i disable postprocess in onnx-export?

### ISSUE THREAD

**Issue by ksv87** [lyuwenyu/RT-DETR#434]
Can i disable postprocess when i export onnx model?

**Comment by lyuwenyu** [comment]
Of course, but you need to modify this file. 
```python
# TODO remove postprocessor
# TODO modify forward args
# TODO modify torch.onnx.export
```
https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetrv2_pytorch/tools/export_onnx.py#L33-L42

**Comment by ksv87** [comment]
thanks, you can say, how its will affect to performance (fps)?

**Comment by lyuwenyu** [comment]
Without the `postprocessor` part, the speed will increase
