### ISSUE TITLE
res2net replaces resnet resulting in degradation of accuracy

### ISSUE THREAD

**Issue by Claraeunice** [lyuwenyu/RT-DETR#44]
Dear Author, Thank you for your excellent work.
The results of rt-detr have attracted a wave of enthusiasts to try it out, and I am no exception.
I was reading the RT-DETR-R50 code when I had the whim to try replacing resnet with res2net in the backbone, but I was surprised to find that it actually lost 10% accuracy!
I don't quite understand why this would happen, shouldn't res2net supposedly work better than resnet ......
Looking forward to your explanation!

**Comment by lyuwenyu** [comment]
Maybe your should tune backbone lr multi carefully

**Comment by Claraeunice** [comment]
> Maybe your should tune backbone lr multi carefully

Thank you for your prompt reply!
Adjusting the list of learning rates seems to bring only tiny gains, but after I replaced resnet with res2net all together, the accuracy loss was huge and those gains still didn't make up the difference. This has piqued my curiosity, but I'd prefer to hear from you, the author, before acting on it.
Looking forward to your advice to minimize the rocks on my way forward!

**Comment by Claraeunice** [comment]
> Maybe your should tune backbone lr multi carefully

Oh, and resnet.py seems to combine the best of the entire resnet family, so no wonder a single replacement doesn't work!

**Comment by Claraeunice** [comment]
> Maybe your should tune backbone lr multi carefully

Oh！resnet.py seems to combine the best of the entire resnet family, so no wonder a single replacement doesn't work!
