### ISSUE TITLE
关于YOLOv6-v9速度不匹配问题

### ISSUE THREAD

**Issue by Peterande** [lyuwenyu/RT-DETR#443]
您好，请问在trt测速的时候，我使用提供的export_onnx的阈值0.7和0.001来依次导出了YOLOv6-v9的engines。
但只有官方代码中提供的v8的速度是匹配的，v6, v7, v9都严重偏慢，比如v6的速度和v8几乎一致。
请问是使用了不同的阈值吗？提高置信度阈值确实会提高速度，但那样不是会掉点吗？

**Comment by lyuwenyu** [comment]
> 阈值0.7和0.001来

得看下他们报告里提供的精度是在设置了那些阈值下得到的，导出时候按照那个来就行。


---

> 提高置信度阈值确实会提高速度，但那样不是会掉点吗？

是的，这也是我们在rtdetr文章中提到的，现在yolo系列的端到端速度和精度报告的一般都不是在一个条件下得到的。
