### ISSUE TITLE
Objects365预训练log或mAP参考

### ISSUE THREAD

**Issue by Peterande** [lyuwenyu/RT-DETR#456]
您好，请问在Objects365预训练时，R18, R50和R101分别在validation的前5000个样本取得多少mAP？好像没有这部分的training log，希望能有一个参考。

**Comment by lyuwenyu** [comment]
obj365相关的log在可以这里找一下 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.7/configs/rtdetr

**Comment by Peterande** [comment]
感谢🙏
