### ISSUE TITLE
请问有没有backbone的预训练参数

### ISSUE THREAD

**Issue by liang-tai** [lyuwenyu/RT-DETR#461]
我看到在整个项目中只有RT-DETR检测器的预训练参数；请问是否有对backbone（如ResNet18）的预训练参数呢

**Comment by Zhao-Yian** [comment]
**Pytorch Backbone weights:**
donwload_url = {
    18: 'https://github.com/lyuwenyu/storage/releases/download/v0.1/ResNet18_vd_pretrained_from_paddle.pth',
    34: 'https://github.com/lyuwenyu/storage/releases/download/v0.1/ResNet34_vd_pretrained_from_paddle.pth',
    50: 'https://github.com/lyuwenyu/storage/releases/download/v0.1/ResNet50_vd_ssld_v2_pretrained_from_paddle.pth',
    101: 'https://github.com/lyuwenyu/storage/releases/download/v0.1/ResNet101_vd_ssld_pretrained_from_paddle.pth',
}

**Paddle Backbone weights:**
https://paddledet.bj.bcebos.com/models/pretrained/ResNet18_vd_pretrained.pdparams
https://bj.bcebos.com/v1/paddledet/models/pretrained/ResNet34_vd_pretrained.pdparams
https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_v2_pretrained.pdparams
https://paddledet.bj.bcebos.com/models/pretrained/ResNet101_vd_ssld_pretrained.pdparams

**Comment by liang-tai** [comment]
好的，感谢
