### ISSUE TITLE
Why does it show "No module named 'src'"?

### ISSUE THREAD

**Issue by jiangsu415** [lyuwenyu/RT-DETR#462]
![image](https://github.com/user-attachments/assets/59eb4be5-83f2-4919-aa0b-3c7b2eef5f08)

**Comment by moosich7** [comment]
hello,I counter same problem，could you tell me how you address this problem?

**Comment by moosich7** [comment]
@jiangsu415 能回忆一下是如何找到错误的根源的吗，找遍全网均没有头绪

**Comment by jiangsu415** [comment]
> @jiangsu415 能回忆一下是如何找到错误的根源的吗，找遍全网均没有头绪

你要不试一下把他放在一个全英文的路径下，我记得当时解决的挺轻松的

**Comment by jiangsu415** [comment]
> @jiangsu415 能回忆一下是如何找到错误的根源的吗，找遍全网均没有头绪

![image](https://github.com/user-attachments/assets/9dd5a719-56e2-4d40-a21e-2db4fffad8b3)
