### ISSUE TITLE
修改图像训练size， 训练异常

### ISSUE THREAD

**Issue by kenh1991** [lyuwenyu/RT-DETR#466]
@lyuwenyu 你好，自有数据，原图为1920*640（w*h）的图片，eval_spatial_size设置为[1920, 640] # h w时，训练3个epoch，指标能到73%， 但是eval_spatial_size修改为[640, 1920] # h w，即原图宽高训练，指标反而无法训练起来，训练30个epoch最高就是0.2的样子，其他设置相同，这个是啥原因呢？
训练配置基于rtdetrv2_r18vd_sp1_120e_coco.yml 修改，
dataloader.yml  train/val {type: Resize, size: [640, 1920]}  #h,w
训练loss到5.7，无法继续下降。
![image](https://github.com/user-attachments/assets/efd283ea-6739-4afe-bdbc-1a328febddaf)
这里是否需要修改呢？谢谢！

**Comment by DaCheng1823** [comment]
你好，我想问一下rt-detr pytorch版本中，resiez是先将图片变640再转tensor还是反着来的呢？

**Comment by kenh1991** [comment]
> 你好，我想问一下rt-detr pytorch版本中，resiez是先将图片变640再转tensor还是反着来的呢？

我是先做resize，最后ToTensor，但是配置文件h,w顺序要注意，反了容易出问题。

**Comment by CPFelix** [comment]
我用rtdetr_pytorch 尺寸为size: [288, 512]时训练loss到7点多就不收敛了，但使用size: [512, 288]就能一直收敛。请问是不是跟grid_wh生成错误有关？  @lyuwenyu @kenh1991
