### ISSUE TITLE
Pytorch checkpoint release

### ISSUE THREAD

**Issue by chuong98** [lyuwenyu/RT-DETR#49]
Hi, thanks for releasing Pytorch code. I checked the github but I can't find the checkpoints for Pytorch, only for Paddle.
Are you planning to release the Pytorch ckpts ? Thank you

**Comment by lyuwenyu** [comment]
I don't have as many gpu source to train from scratch right now. I will convert the paddle version pretrained weights to pytorch.

You can star this repo to keep following news.

**Comment by ibims1entwickler** [comment]
Can you estimate when the pytorch weights will be available and pytorch code fully aligned with paddlepaddle code?
