### ISSUE TITLE
Clarification about label preprocessing

### ISSUE THREAD

**Issue by amirbakhtiary23** [lyuwenyu/RT-DETR#491]
Hi, thank you for your great contribution.
As you have mentioned in  [#99 ](https://github.com/lyuwenyu/RT-DETR/issues/99#issuecomment-1779196475) target boxes are converted to `XYXY` then to `CXCY`. 
But i cannot find exactly where does this conversion to `CXCY` happens. Can you please point it out to me? I found where the `CXCY` to `XYXY` take place for computing loss value, but I need to write my own Dataloader in order to train on my custom fusion dataset so I need to know where does the first conversion take place.

**Comment by lyuwenyu** [comment]
1. config: https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetrv2_pytorch/configs/rtdetrv2/include/dataloader.yml#L14
2. code: https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetrv2_pytorch/src/data/transforms/_transforms.py#L93-L113

**Comment by amirbakhtiary23** [comment]
Thank you very much.

**Comment by duang33** [comment]
> 1. config: https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetrv2_pytorch/configs/rtdetrv2/include/dataloader.yml#L14
> 2. code: https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetrv2_pytorch/src/data/transforms/_transforms.py#L93-L113

作者您好，我想问一下，我现在自己写的直接读取ndarray而不是用Image类来迭代输入图像，我就需要自己将ann中的bbox手动转换为cxcywh的形式输入至网络中，然后计算loss的时候还需要再转换到xyxy的形式吗？
