### ISSUE TITLE
请问密集小目标场景下，要在哪里设置每张图的最大目标数量max detection number？

### ISSUE THREAD

**Issue by ucsdzehualiu** [lyuwenyu/RT-DETR#497]
**Star RTDETR**
请先在RTDETR主页点击**star**以支持本项目
Star RTDETR to help more people discover this project. 

---

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Comment by lyuwenyu** [comment]
https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetrv2_pytorch/configs/rtdetrv2/include/rtdetrv2_r50vd.yml#L69

**Comment by ucsdzehualiu** [comment]
感谢
