### ISSUE TITLE
请教rtdetr_r50vd.yml文件中的一些参数设置。

### ISSUE THREAD

**Issue by TaroPlay** [lyuwenyu/RT-DETR#50]
作者你好，我看到rtdetr_r50vd.yml文件中有两个300的参数，分别是RTDETRTransformer: num_queries: 300和 DETRPostProcess: num_top_queries: 300。
我想请问这两个300分别表示什么，原论文中写到在IoU aware query selection中选取了Top K 个分数，文中K=300，请问论文中的K=300是代码中的哪个参数，num_queries还是num_top_queries?以及最后预测头会预测出多少个预测框和GT进行匹配？
期待你的答复

**Comment by TaroPlay** [comment]
好的，意思就是selection中选出了分数最高的300个，对应代码中的num_queries.然后最终也是300个预测框和GT去做匹配。那根据数据集类别数的不同，num_queries和num_top_queries是不是可以修正，而且可以递减（比如query 200个，后处理的时候是100个）？



> 1. iouri topk 对应的是 query的数量 也就是num_queries
> 2. num_top_queries是在后处理里 意思是在1中的num_queries中再去选择k个作为最终的结果 （只不过在rtdetr里这两个数设置的一样）

**Comment by lyuwenyu** [comment]
是的 都可以改的  可以在自己的数据集上做做实验对比一下

**Comment by TaroPlay** [comment]
好的，感谢回复，我没有问题了
