### ISSUE TITLE
Seems scailing input format config doesn't work

### ISSUE THREAD

**Issue by jeonghyunjo** [lyuwenyu/RT-DETR#506]
Hi,

I modified dataloader.yml file's configuration but it doesn't change the input format.
`        - {type: ConvertPILImage, dtype: 'float32', scale: True}   `

I changed scale factor from True to False, but still input format is the range of 0.0 to 1.0. 
How to disable input value scale factor?

**Comment by lyuwenyu** [comment]
I tried and didn't find the problem you mentioned

<img width="500" alt="image" src="https://github.com/user-attachments/assets/2ba6e8c1-5ee7-47ad-b82b-6f96717c97cd">


---

```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
pytorch-wpe               0.0.1
torch                     2.4.0
torch-complex             0.4.4
torchaudio                2.4.0
torchsde                  0.2.6
torchvision               0.19.0
```

**Comment by jeonghyunjo** [comment]
Sorry I took a look at the whole package and it was my mistake. I will close this ticket. Thank you!
