### ISSUE TITLE
迁移到时空动作检测任务

### ISSUE THREAD

**Issue by Shu-Ang** [lyuwenyu/RT-DETR#522]
作者您好，我想把RT-DETR用于时空动作检测(spatial-temporal action detection)中，使用AVA格式的数据集训练，输入是1920*1080图片。
目前只做了如下修改：1、dataset部分修改为AVA格式；2、backbone部分改为resnet3D；3、eval部分修改为AVAMetric；
训练时loss正常下降，但是验证时mAP都是0。请问与输入尺寸不是正方形有关吗？或者您还有什么其他建议？
![image](https://github.com/user-attachments/assets/3adc220a-fe04-4a94-b545-1f1b88e1c451)
Hello author, I would like to use RT-DETR for spatial-temporal action detection, training on a dataset in AVA format with an input of 1920*1080 images.
Only the following changes have been made: 1. dataset was changed to AVA format. 2. The backbone part is changed to resnet3D; 3. eval modified to AVAMetric;
loss decreased normally during training, but mAP was 0 during verification. Is it related to the fact that the input size is not square? Or do you have any other suggestions?

**Comment by lyuwenyu** [comment]
这里都改了嘛；另外建议先用640的图简单训练一下，看看流程和结果

https://github.com/lyuwenyu/RT-DETR/blob/0b6972de10bc968045aba776ec1a60efea476165/rtdetrv2_pytorch/configs/rtdetrv2/include/rtdetrv2_r50vd.yml#L9

**Comment by Shu-Ang** [comment]
> 这里都改了嘛；另外建议先用640的图简单训练一下 看看流程和结果；没问题的话再精调一下
> 
> https://github.com/lyuwenyu/RT-DETR/blob/0b6972de10bc968045aba776ec1a60efea476165/rtdetrv2_pytorch/configs/rtdetrv2/include/rtdetrv2_r50vd.yml#L9

确实是图像尺寸的问题，我将数据集中1920*1080的图片裁剪成1080*1080，eval_size改成[256, 256]，验证时map值是正常的。rtdetr可以用矩形图像验证吗？需要修改哪些地方？

**Comment by Shu-Ang** [comment]
> > 这里都改了嘛；另外建议先用640的图简单训练一下 看看流程和结果；没问题的话再精调一下
> > https://github.com/lyuwenyu/RT-DETR/blob/0b6972de10bc968045aba776ec1a60efea476165/rtdetrv2_pytorch/configs/rtdetrv2/include/rtdetrv2_r50vd.yml#L9
> 
> 确实是图像尺寸的问题，我将数据集中1920_1080的图片裁剪成1080_1080，eval_size改成[256, 256]，验证时map值是正常的。rtdetr可以用矩形图像验证吗？需要修改哪些地方？

问题解决了。我将训练和验证的处理过程改成一致：将1920*1080 resize成448*256，keep_ratio=False，eval_size=[256,448]。验证时map正常
