### ISSUE TITLE
一些关于IOU-aware Query Selection 的疑问

### ISSUE THREAD

**Issue by ValiantDiligent** [lyuwenyu/RT-DETR#526]
RT-DETR是个很了不起的工作，在研究源码和论文的时候，我有一些疑问，想请教一下。
1、论文里面的方程2（defined as the discrepancy between the predicted distributions of localization P and classification C in Eq2）似乎在源码里面似乎并没有显式地体现。我注意到分类loss是用了VarifocalLoss，但我并不能很理解为什么这里面包含了Eq2. 对于IOU-aware Query Selection，我的理解是cls_loss用VarifocalLoss替代，将iou考虑进分类损失里面。
2、注意到在Query Setect部分（rt_decoder.py中的_get_decoder_input），创建了很多个anchor，我不知道这个设置是否和IOU-aware Query Selection有关。
麻烦了

**Comment by lyuwenyu** [comment]
1. 你可以理解`IOU-aware Query Selection`是我们提出的一种概念；`vfl`是一种实现形式，因为这个loss里也考虑了位置信息；当然也可以换成其他的计算方式 
2. 这快不是的；是encoder用的  为了得到query box
