### ISSUE TITLE
loss_masks

### ISSUE THREAD

**Issue by NeKoooo233** [lyuwenyu/RT-DETR#54]
请问下，
![image](https://github.com/lyuwenyu/RT-DETR/assets/60842553/f76b55a5-ae46-4d30-af09-46962439ac60)
在此文件夹里的loss_masks中有几个函数是未定义的，是因为这个loss不重要，所以省略过去了吗

**Comment by NeKoooo233** [comment]
目前还没有安装onnx

**Comment by lyuwenyu** [comment]
嗯检测任务用不到那些方法  不影响
