### ISSUE TITLE
4卡学习率为0.0001，那么单卡应该除以4吗

### ISSUE THREAD

**Issue by Claraeunice** [lyuwenyu/RT-DETR#79]
对于学习率调整我比较疑惑，学习率是与batchsize还是卡数成比例线性缩放呢

**Comment by Claraeunice** [comment]
还想问问，单卡跑的话，在rtdetr_reader.yml中的work_num要改成1吗

**Comment by lyuwenyu** [comment]
LR建议不改    BS可以随便改

**Comment by Claraeunice** [comment]
> LR建议不改 BS可以随便改

好的，感谢！我还想问问参数量和计算量输出的事情（在#72）
