### ISSUE TITLE
Training custom dataset and get weird output bounding boxes?

### ISSUE THREAD

**Issue by ledinhtri97** [lyuwenyu/RT-DETR#88]
Hello, thank you for great work.

I am training your rtdetr_pytorch with config "rtdetr_r18vd_coco.yml"
number class is 1.

tuning from model: "rtdetr_r18vd_5x_coco_objects365_from_paddle.pth"
the dataset I update with:
```
num_classes: 1
remap_mscoco_category: False
```
After 100epoches,  model is the most best eval at the epoch 51.

I checked the output I inferenced by onnx from  look weird for me (it should be at the nose location), when its look like output. Am I missing something? thank you so much
```
output = session.run(
    output_names=output_names,
    input_feed={"images": im_data.data.numpy(), "orig_target_sizes": np.array([input_shape])}
)
labels, boxes, scores = output
thrh = 0.5
for i in range(im_data.shape[0]):
    scr = scores[i]
    filter_scr = scr > thrh
    lab = labels[i][filter_scr]
    box = boxes[i][filter_scr]
    print(i, sum(filter_scr))
    for b in box:
        draw.rectangle(list(b), outline="red",)
        draw.text((b[0], b[1]), text=str(lab[i]), fill="blue", )
```

![image](https://github.com/lyuwenyu/RT-DETR/assets/16860306/37891e37-378c-4590-9ee1-73adb8ffbb28)

**Comment by lyuwenyu** [comment]
Please check below settings
1. the format `orig_target_sizes` is `[w, h]`
2. the data processing you should follow [this](https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetr_pytorch/configs/rtdetr/include/dataloader.yml#L33-L35), and draw output box on origin image (not processed data)

**Comment by ledinhtri97** [comment]
Hi @lyuwenyu thank you for quick respone.

I forgot to mention that. I also try same code inference and change model is convert only from "rtdetr_r18vd_5x_coco_objects365_from_paddle.pth" and got correct bounding result

"orig_target_sizes": np.array([input_shape]
the input_shape = [640, 640]
![image](https://github.com/lyuwenyu/RT-DETR/assets/16860306/012027a7-4d92-4c2d-b37c-ff67f88f5762)

full code inference:

```
providers = ["CUDAExecutionProvider", "CPUExecutionProvider"]
session = ort.InferenceSession(model_path, providers=providers)
output_names = [x.name for x in session.get_outputs()]
input_shape = [640, 640]
im = Image.open(im_path).convert("RGB")
im = im.resize((input_shape[0], input_shape[1]))
draw = ImageDraw.Draw(im)

im_data = ToTensor()(im)[None]
output = session.run(
    output_names=output_names,
    input_feed={"images": im_data.data.numpy(), "orig_target_sizes": np.array([input_shape])}
)

labels, boxes, scores = output
thrh = 0.5
for i in range(im_data.shape[0]):
    scr = scores[i]
    filter_scr = scr > thrh
    lab = labels[i][filter_scr]
    box = boxes[i][filter_scr]
    print(i, sum(filter_scr))
    for b in box:
        draw.rectangle(list(b), outline="red",)
        draw.text((b[0], b[1]), text=str(lab[i]), fill="blue", )
```

**Comment by ledinhtri97** [comment]
@lyuwenyu I had figueout the problem from dataset. then it should be fine with he model
