### ISSUE TITLE
关于恢复训练

### ISSUE THREAD

**Issue by NeKoooo233** [lyuwenyu/RT-DETR#97]
您好，在solver.py文件中，是先初始化，后resume，这样是用checkpoints的配置全部取代初始化的cfg吗
目前训练了一半，我改变了pe_temperature和dn_group的数量，在恢复训练时会被正确加载吗
如果不能正确加载，是否可以利用tuning的代码，还是只能从头开始训练了？

**Comment by lyuwenyu** [comment]
1. 可以resume,  checkpoint里不存模型的配置相关的参数  只有state_dict   
2. 但是`改变了pe_temperature和dn_group的数量，` 会导致训练时候模型结构发生了变化   resume和从头训练 到最后是不等价的

**Comment by lyuwenyu** [comment]
你可以star一下这个repo  有问题再留意

**Comment by NeKoooo233** [comment]
> 1. 可以resume,  checkpoint里不存模型的配置相关的参数  只有state_dict
> 2. 但是`改变了pe_temperature和dn_group的数量，` 会导致训练时候模型结构发生了变化   resume和从头训练 到最后是不等价的

非常感谢您的解答
